import { makeStyles } from "@material-ui/styles";
export const useStyles = makeStyles((theme) => ({
  container: {
    backgroundColor: "#F7F8FC",
    height: "100%",
    minHeight: "100vh",
  },
  link: {
    fontFamily: "Muli",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 14,
    letterSpacing: "0.4px",
    color: "#3751FF",
    textAlign: "right",
    marginRight: 25,
  },
  subtitle: {
    fontFamily: "Muli",
    fontStyle: "normal",
    fontWeight: "normal",
    fontSize: 12,
    lineHeight: "16px",
    letterSpacing: "0.1px",
    color: "#FFFFFF",
    marginLeft: 20,
  },
  subtitle2: {
    color: "#FFFFFF",
    marginLeft: 5,
  },
  title: {
    fontFamily: "Muli",
    fontStyle: "normal",
    fontWeight: "bold",
    fontSize: 19,
    lineHeight: "24px",
    letterSpacing: "0.4px",
    color: "#87EC21",
    marginLeft: 20,
  },
  itemTitle: {
    fontFamily: "Muli",
    fontStyle: "normal",
    fontWeight: "600",
    fontSize: 16,
    lineHeight: "20px",
    letterSpacing: "0.2px",
    color: "#E0EC21",
    marginLeft: 20,
    marginButton: 10,
  },
  itemValue: {
    color: "#9FA2B4",
    fontFamily: "Mulish",
    fontStyle: "normal",
    fontWeight: 600,
    fontSize: "14px",
    lineHeight: "20px",
    textAlign: "right",
    letterSpacing: "0.4px",
  },
  lastRow: {
    marginTop: -30,
  },
  tablecard: {
    backgroundColor:"#313040",
    border: "1px solid #DFE0EB",
    borderRadius: 15,
    padding: "24px 4px 24px 0px",
  },
  mainBlock: {
    padding: 90,
    marginLeft: 255,
    "@media (max-width: 1080px)": {
      marginLeft: 0,
      padding: 10,
    },
  },
}));
